# This file defines GitHub App credentials used by Backstage/RHDH.
# It is included from app-config.local.yaml using:
# $include: ../extra-files/github-app-credentials.yaml
#
# You can generate the values using:
#   npx @backstage/cli create-github-app <github-org-name>
# Then rename this file to github-app-credentials.yaml

appId: ${GITHUB_APP_APP_ID}
clientId: ${GITHUB_APP_CLIENT_ID}
clientSecret: ${GITHUB_APP_CLIENT_SECRET}
webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
privateKey: ${GITHUB_APP_PRIVATE_KEY}
