# site_name: backstage
# docs_dir: docs
# plugins:
#   - techdocs-core

site_name: red-hat-developer-hub
site_description: Red Hat Developer Hub
site_author: user:user
docs_dir: docs
plugins:
  - techdocs-core
nav:
  - "Welcome To Red Hat Developer Hub": index.md

  
