includes:
  - dynamic-plugins.default.yaml
plugins:
  # EXAMPLES:
  # loading image from container image
   - package: oci://docker.io/tomaskral/simple-chat:v0.0.1!internal-backstage-plugin-simple-chat
     disabled: false
     pluginConfig:
       dynamicPlugins:
         frontend:
             internal.backstage-plugin-simple-chat:
               appIcons:
                 - name: chatIcon
                   importName: ChatIcon
               dynamicRoutes:
                 - path: /simple-chat
                   importName: SimpleChatPage
                   menuItem:
                     text: 'Simple Chat'
                     icon: chatIcon

  # # loading image from tarball URL
  # - disabled: false
  #   package: >-
  #       https://github.com/redhat-developer/rhdh-plugin-export-backstage-community-plugins/releases/download/v1.2.0/backstage-community-plugin-tech-insights-dynamic-0.3.28.tgz
  #   integrity: sha512-cNHXSwPa5fOi2BcNVSe7tfdLyM0JY988CE5t+P9p/XlboP1QpQbMcLBmqPrlXZdpedAyp81Zz3yPQYGnPuy9ww==
  #   pluginConfig:
  #     dynamicPlugins:
  #       techInsights:
  #         factRetrievers:
  #           entityOwnershipFactRetriever:
  #             cadence: '*/15 * * * *'
  #             lifecycle: { timeToLive: { weeks: 2 } }
  #           entityMetadataFactRetriever:
  #             cadence: '*/15 * * * *'
  #             lifecycle: { timeToLive: { weeks: 2 } }
  #           techdocsFactRetriever:
  #             cadence: '*/15 * * * *'
  #             lifecycle: { timeToLive: { weeks: 2 } }
  #           apiDefinitionFactRetriever:
  #             cadence: '*/15 * * * *'
  #     lifecycle: { timeToLive: { weeks: 2 } }

  # # loading plugin from directory inside the RHDH container
  # - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac
  #   disabled: true
  #   pluginConfig:
  #     dynamicPlugins:
  #       frontend:
  #         janus-idp.backstage-plugin-rbac:
  #           mountPoints:
  #             - mountPoint: admin.page.rbac/cards
  #               module: RbacPlugin
  #               importName: RbacPage
  #               config:
  #                 layout:
  #                   gridColumn: "1 / -1"
  #                   width: 100vw
  #                 props:
  #                   useHeader: false
  #           dynamicRoutes:
  #             - path: /admin/rbac
  #               module: RbacPlugin
  #               importName: RbacPage
